# Generated by Django 4.1.7 on 2023-03-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('opening_hours', models.JSONField(default={'friday': {'close': '18:00', 'open': '08:00'}, 'monday': {'close': '18:00', 'open': '08:00'}, 'sunday': {'close': '18:00', 'open': '08:00'}, 'thursday': {'close': '18:00', 'open': '08:00'}, 'tuesday': {'close': '18:00', 'open': '08:00'}, 'wednesday': {'close': '18:00', 'open': '08:00'}}, verbose_name='Opening hours')),
            ],
        ),
    ]
