# Generated by Django 4.1.7 on 2023-03-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='opening_hours',
            field=models.JSONField(null=True),
        ),
    ]
