# Generated by Django 4.1.7 on 2023-03-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='opening_hours',
        ),
        migrations.AddField(
            model_name='salon',
            name='details',
            field=models.TextField(default='dupa'),
            preserve_default=False,
        ),
    ]
