# Generated by Django 4.1.7 on 2023-03-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_salon_opening_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='opening_hours',
            field=models.JSONField(default={'friday': {'close': '18:00', 'open': '08:00'}, 'monday': {'close': '18:00', 'open': '08:00'}, 'sunday': {'close': '18:00', 'open': '08:00'}, 'thursday': {'close': '18:00', 'open': '08:00'}, 'tuesday': {'close': '18:00', 'open': '08:00'}, 'wednesday': {'close': '18:00', 'open': '08:00'}}, verbose_name='Opening hours'),
        ),
    ]
