# Generated by Django 4.1.7 on 2023-03-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='for_all',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='for_client',
        ),
    ]
