# Generated by Django 4.1.7 on 2023-03-25 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_remove_eventtype_for_all_remove_eventtype_for_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
