# Generated by Django 4.1.7 on 2023-03-13 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posytion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posytion', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('F', 'Fryzjerka'), ('R', 'Recepcjonistka'), ('S', 'Superviser')], default='S', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='addnewuser',
            name='admin',
        ),
        migrations.AddField(
            model_name='addnewuser',
            name='user_posytion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.posytion'),
        ),
    ]
