# Generated by Django 4.1.7 on 2023-03-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_addnewuser_user_posytion_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('F', 'Fryzjerka'), ('R', 'Recepcjonistka'), ('S', 'Superviser')], default='S', max_length=20),
        ),
    ]
