# Generated by Django 4.1.7 on 2023-03-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
    ]
