# Generated by Django 4.1.7 on 2023-03-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis')),
                ('day', models.DateField(verbose_name='Dzień')),
                ('start_time', models.TimeField(verbose_name='Początek')),
                ('end_time', models.TimeField(verbose_name='Koniec')),
            ],
        ),
    ]
