# Generated by Django 4.1.7 on 2023-03-25 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_alter_eventtype_duration'),
        ('cal', '0003_alter_event_day_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prices.eventtype'),
        ),
    ]
